// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

//
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCexgKmdAzK4g6zBx3qhwbhxCg8nyVyUg',
    appId: '1:463988413810:web:b7af76ebc8472b1f30b9eb',
    messagingSenderId: '463988413810',
    projectId: 'madartfolioapp',
    authDomain: 'madartfolioapp.firebaseapp.com',
    storageBucket: 'madartfolioapp.appspot.com',
    measurementId: 'G-JNBL3BCRZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApVIVvSJEDe-61qDF5rbTC5bwx-NHtPSg',
    appId: '1:463988413810:android:4bf958ff353b915830b9eb',
    messagingSenderId: '463988413810',
    projectId: 'madartfolioapp',
    storageBucket: 'madartfolioapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8oBI-Xlu55PMftjOeg7JqMyyriCNPwT4',
    appId: '1:463988413810:ios:8dab82fd91c332ec30b9eb',
    messagingSenderId: '463988413810',
    projectId: 'madartfolioapp',
    storageBucket: 'madartfolioapp.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8oBI-Xlu55PMftjOeg7JqMyyriCNPwT4',
    appId: '1:463988413810:ios:8dab82fd91c332ec30b9eb',
    messagingSenderId: '463988413810',
    projectId: 'madartfolioapp',
    storageBucket: 'madartfolioapp.appspot.com',
    iosBundleId: 'com.example.messagingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCexgKmdAzK4g6zBx3qhwbhxCg8nyVyUg',
    appId: '1:463988413810:web:9e592a20c178a83a30b9eb',
    messagingSenderId: '463988413810',
    projectId: 'madartfolioapp',
    authDomain: 'madartfolioapp.firebaseapp.com',
    storageBucket: 'madartfolioapp.appspot.com',
    measurementId: 'G-L3MHZHR6R4',
  );
}
